### ISSUE TITLE
current season historica scrapping did not work for tennis match

### ISSUE THREAD

**Issue by ccqqkk** [jordantete/OddsHarvester#23]
Hi Jordan,

While trying to run multi-league fetch with more recent data, I started using `--season 2025` and found this opens the wrong web page. This is the same issue as https://github.com/jordantete/OddsHarvester/issues/7 and I think the solution was to change "2025" to "current". However, why I tried it with current, the log responded with error of "current" being invalid value for season.

command:
`uv run python src/main.py scrape_historic --sport tennis --season current --markets "match_winner,over_under_games_22_5" --league "wta-london,wta-wuhan,wta-zhuhai" --format csv --file_path tennis_wta_2025_real.csv --preview_submarkets_only --headless`

Error log:
`2025-08-30 20:03:56,142 - CLIArgumentHandler - ERROR - CLI args validation failed: Invalid season format: 'current'. Expected format: YYYY or YYYY-YYYY (e.g., 2024 or 2024-2025).`

Can you please have a look?

**Comment by ccqqkk** [comment]
I have tried the "omit season" approach and I got an other error:
`error: the following arguments are required: --season`

**Comment by jordantete** [comment]
Hi, thanks again for pointing this out!

You’re absolutely right, this was a regression on my side. I’ve just pushed a fix so that the `--season` current flag works again as intended.

For your case, you can now run:
```
uv run python src/main.py scrape_historic \
  --sport tennis \
  --season current \
  --leagues "wta-london,wta-wuhan,wta-zhuhai" \
  --markets "match_winner,over_under_games_22_5" \
  --format csv \
  --file_path tennis_wta_2025_real.csv \
  --headless
```

This will correctly scrape the current season for the leagues you specified.

**Comment by ccqqkk** [comment]
Hi Jordan, thanks for the work and I can see the difference. However, it seems that `current` still doesn't pass all your validation conditions. The error I'm getting now is:

`2025-09-02 21:48:21,559 - ScraperApp - INFO - [73/85] Processing league: wta-sydney
2025-09-02 21:48:21,559 - ScraperApp - ERROR - Non-retryable error encountered: Invalid season format: current. Expected format: 'YYYY' or 'YYYY-YYYY'`
